# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  # Configuración del proveedor VirtualBox
  config.vm.provider :virtualbox do |vb|
    vb.gui = false
  end

  # Configuracion de firewall
  config.vm.define :firewall do |firewall|
    firewall.vm.box = "juanmena1605/dns-firewall"  # Especifica la caja para Ubuntu 22.04
    firewall.vm.network :private_network, ip: "192.168.50.4"
    firewall.vm.hostname = "firewall"
  end

  # Configuración del maestro
  config.vm.define :maestro do |maestro|
    maestro.vm.box = "juanmena1605/dns-maestro"  # Especifica la caja para Ubuntu 22.04
    maestro.vm.network :private_network, ip: "192.168.50.3"
    maestro.vm.hostname = "maestro"
  end

  # Configuración del esclavo
  config.vm.define :esclavo do |esclavo|
    esclavo.vm.box = "juanmena1605/dns-esclavo"  # Especifica la caja para Ubuntu 22.04
    esclavo.vm.network :private_network, ip: "192.168.50.2"
    esclavo.vm.hostname = "esclavo"
  end
end
